on: push
jobs:
  testing-custom-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "LS"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
